### ISSUE TITLE
scoring in spamassassin

### ISSUE THREAD

**Issue by mgrant0** [bigio/spamassassin-esp#1]
To test this, I put Esp.cf and Esp.pm in my /etc/spamassassin/ directory.  I added this to cron:

```
* * * * * (cd /etc/mail/spamassassin; wget -q -N http://www.invaluement.com/spdata/sendgrid-id-dnsbl.txt  http://www.invalue\
ment.com/spdata/sendgrid-envelopefromdomain-dnsbl.txt)

```
I added this to /etc/spamassassin/local.cf:

```
loadplugin Mail::SpamAssassin::Plugin::Esp Esp.pm
score    SPBL_SENDGRID 7.5
```

I then run a test message through `spamassassin -t` which I know is in sendgrid-id-dnsbl.txt.  The envelope from of the message has:

```
From bounces+14884758-c470-contact=beat.net@sendgrid.net  Tue Oct 13 12:35:07 2020
```

I verified that the message indeed has the `X-SG-EID` header.  

But I never see the score in the spamassassin markup.

What am I doing wrong?  Do I have the lines correct in local.cf?

It would be great to have a working example of what to put in local.cf in the readme.

**Comment by bigio** [comment]
There is a complete example in Esp.cf file, I will improve man page in future version.

**Comment by mgrant0** [comment]
I fixed it, you are missing the `score` lines in Esp.cf.

**Comment by mgrant0** [comment]
But this rbl dns query:

```
  askdns   RBL_SENDGRID_ID _SENDGRIDID_.rblid.domain.tld A 127.0.0.2
```

This can't work yet like this, is there a dnsrbl for this data yet? and doesn't having this stuff in the local file obviate the need for this lookup?

**Comment by mgrant0** [comment]
Here is my working example (only for sendgrid) that I added to local.cf:

```
loadplugin Mail::SpamAssassin::Plugin::Esp Esp.pm
ifplugin Mail::SpamAssassin::Plugin::Esp
sendgrid_feed /etc/mail/spamassassin/sendgrid-id-dnsbl.txt
sendgrid_domains_feed /etc/mail/spamassassin/sendgrid-envelopefromdomain-dnsbl.txt
header   SPBL_SENDGRID          eval:sendgrid_check()
describe SPBL_SENDGRID          Message from Sendgrid abused account
score    SPBL_SENDGRID 7.5
endif plugin Mail::SpamAssassin::Plugin::Esp
```

note, this config is by dropping the Esp.cf and Esp.pm files directly into /etc/spamassassin for testing.  The reason I was having problems was that it's purely because I'm not fully installing this into spammassassin yet.  It wasn't reading the Esp.cf file and hence only putting a score in my local.cf doesn't work.

**Comment by bigio** [comment]
> I fixed it, you are missing the `score` lines in Esp.cf.

This is on purpose, everybody will choose its preferred score.

**Comment by bigio** [comment]
> But this rbl dns query:
> 
> ```
>   askdns   RBL_SENDGRID_ID _SENDGRIDID_.rblid.domain.tld A 127.0.0.2
> ```
> 
> This can't work yet like this, is there a dnsrbl for this data yet? and doesn't having this stuff in the local file obviate the need for this lookup?

At least Invaluement has such list and everybody can create one on his own;
a direct lookup will have id immediately available while the .txt file is updated hourly.
If you are using the rbl you have no need to use load the .txt feed txt file.

**Comment by mgrant0** [comment]
Please let me propose some edits.  I'm going to clone and do you a pull request.

**Comment by mgrant0** [comment]
When you query by rbl in the AskDNS section, don't you need some sort of meta rule to add a score?  Do you have an example of that?  Something like this (untested):

```
  meta RBL_SENDGRID (RBL_SENDGRID_ID || RBL_SENDGRID_DOM)
  score RBL_SENDGRID 7.5
```

**Comment by bigio** [comment]
When you use direct queries RBL_SENDGRID rule is used only to set the tag, you should score the askdns rule instead.
