### ISSUE TITLE
Feature request: add Klaviyo

### ISSUE THREAD

**Issue by gertvdijk** [bigio/spamassassin-esp#11]
Would be nice to see support for [Klaviyo](https://www.klaviyo.com/). Accounts on their platform can be identified by the `X-Kmail-Account` header value, I think.

Headers from an example mail - phishing - by likely compromised Klaviyo account (Moon Pod webshop):

```
Return-Path: <msprvs1=19709fLFymiMk=bounces-304613-225643@xrywlw.shared.klaviyomail.com>
From: "Portfolio Security" <security@moonpod.co>
Subject: Secure your Portfolio
X-Kmail-Message: 01HHBT7T7D10HVT8BX2Q0C99KY
X-Kmail-Account: HaDCVL
X-Kmail-Ops: 01HHBQG[...]
List-Unsubscribe: <mailto:unsubscribe@unsub.spmta.com?subject=unsubscribe:tGm4[...]>
List-Id: <spc.304613.225643.sparkpostmail.com>
```

(`[...]` is where I truncated some values.)

`HaDCVL` is one that I blocked for phishing, `RhNmWN` is one that I've seen for sending unsolicited offers.

Thanks!

**Comment by bigio** [comment]
[Klaviyo](https://www.klaviyo.com/) seems to use Sparkpost to send emails, listing bad customers in Sparkpost list should be enough.

**Comment by gertvdijk** [comment]
Thanks, but it's not only Sparkpost being used. I see also emails from other ESPs like Sendgrid used in the very same phishing campaign.

```
Received: from o1274.shared.klaviyomail.com (o1274.shared.klaviyomail.com [167.89.11.11])
        (using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
         key-exchange X25519 server-signature RSA-PSS (4096 bits) server-digest SHA256)
[...]
Return-Path: <bounces+10249095-38b1-[...]=startmail.com@send.ksd3.klaviyomail.com>
From: Portfolio Security <security@moonpod.co>
Subject: Secure your Portfolio
X-Kmail-Message: 01HHBT7T7D10HVT8BX2Q0C99KY
X-Kmail-Ops: 01HHBR[...]
X-Kmail-Account: HaDCVL
X-SG-EID: [...]
X-SG-ID: [...]
```

`X-Kmail-Account: HaDCVL` is the identifier for me here to stop the phishing campaign.

I don't know how Klaviyo works - perhaps they distribute over several larger ESPs?

They [don't answer me](https://twitter.com/gertvdijk/status/1734213626507014627) on Twitter/X, by the way.
