### ISSUE TITLE
If you define sendgrid_id_rbl or sendgrid_dom_rbl you get an error

### ISSUE THREAD

**Issue by mgrant0** [bigio/spamassassin-esp#3]
There's a typo on Esp.cf.  Shouldn't have an '=' to set the values in the cf file.  

Also there should be a check to make sure the user doesn't use both rbl and files methods.

**Comment by bigio** [comment]
There shouldn't be a check, I want to be possible to use both invaluement.com dnsbl and a local .txt file for sendgrid id and domains.

**Comment by mgrant0** [comment]
Sure, you can take out that code then.  You then also probably want to change the comment at the top of the cf file to make that more clear.  What do you think about stating "Typically either the files or the rbl method is used but you may use both.  In that case though, the scores become additive so you may need to adjust them accordingly".  

If you wanted to get a little more complex, the files rules can be added to the meta rule for the rbl.

**Comment by bigio** [comment]
Better comment in commit 3f173c88c35bbd6bea86dc8d323ebacc071e712b
