### ISSUE TITLE
Reloading after text file changes

### ISSUE THREAD

**Issue by LeMurphant** [bigio/spamassassin-esp#5]
I am less familiar with using .txt lists directly in the spamassassin rules.

Our default behaviour was to restart SpamAssassin any time there is a change in the text files but this is happening more often than we would like, is a reload sufficient to load the new values? Is it even necessary to reload when the files change?

**Comment by bigio** [comment]
To reload new values in Esp and Phishing plugin (both plugins read data from a .txt file) reloading SpamAssassin is enough.
